/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.locadora.telas;

import br.com.locadora.dal.ModuloConexao;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class TelaNovaLocacao extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public TelaNovaLocacao() {
        initComponents();
        conexao = ModuloConexao.conector();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codLoc = new javax.swing.JTextField();
        BtnPesqCli = new javax.swing.JButton();
        btnPesqDvd = new javax.swing.JButton();
        desktopPesq = new javax.swing.JDesktopPane();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Código Locação");

        BtnPesqCli.setText("Pesquisar Cliente");
        BtnPesqCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesqCliActionPerformed(evt);
            }
        });

        btnPesqDvd.setText("Pesquisar Titulos");
        btnPesqDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqDvdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopPesqLayout = new javax.swing.GroupLayout(desktopPesq);
        desktopPesq.setLayout(desktopPesqLayout);
        desktopPesqLayout.setHorizontalGroup(
            desktopPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        desktopPesqLayout.setVerticalGroup(
            desktopPesqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton3.setText("Consultar Locação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnPesqCli)
                    .addComponent(btnPesqDvd)
                    .addComponent(jButton3))
                .addGap(30, 30, 30)
                .addComponent(desktopPesq)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(codLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(BtnPesqCli)
                        .addGap(45, 45, 45)
                        .addComponent(btnPesqDvd)
                        .addGap(59, 59, 59)
                        .addComponent(jButton3)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addComponent(desktopPesq))
                .addContainerGap())
        );

        setBounds(0, 0, 620, 416);
    }// </editor-fold>//GEN-END:initComponents


    private void BtnPesqCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesqCliActionPerformed
        // Aqui chama a Tela de Pesquisar Cliente TelaPescCli
        TelaPesqCli pesCli = new TelaPesqCli();
        pesCli.setVisible(true);
        desktopPesq.add(pesCli);
        try {
            pesCli.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaNovaLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnPesqCliActionPerformed

    private void btnPesqDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqDvdActionPerformed
        // Aqui chama a Tela de Pesquisa de TiTulos
        TelaPesqDvd pesDvd = new TelaPesqDvd();
        pesDvd.setVisible(true);
        desktopPesq.add(pesDvd);
        try {
            pesDvd.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(TelaNovaLocacao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesqDvdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPesqCli;
    private javax.swing.JButton btnPesqDvd;
    private javax.swing.JTextField codLoc;
    private javax.swing.JDesktopPane desktopPesq;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
